In [1]:
import refinitiv.data as rd
import pandas as pd
import numpy as np
import time
import warnings

warnings.filterwarnings('ignore', category=FutureWarning)

rd.open_session()

## Indeksin faktoreiden haku

In [2]:
# chunk = 50

universe = [".STOXX"]

fields = [
    "TR.Index_PE_RTRS",
    "TR.Index_PRICE_TO_BOOK_RTRS",
    "TR.Index_DIV_YLD_RTRS",
    "TR.PriceClose"
]

# Manuaalisesti 

results = []

# for i in range(0, len(universe), chunk):
#     chunk_universe = universe[i:i + chunk]
#     df_index = rd.get_history(
#         universe=chunk_universe,
#         fields=fields,
#         start="2023-01-01",
#         end="2026-03-05",
#         interval="1D"  
#     )
#     results.append(df_index)
#     time.sleep(1)  # Odota hetki ennen seuraavaa pyyntöä

df_index = rd.get_history(
    universe=universe,
    fields=fields,
    start="2023-01-01",
    end="2026-03-05",
    interval="1D"  
)

display(df_index.head())

.STOXX,Calculated PE Ratio,Calculated Price to Book,Calculated Index Dividend Yield,Price Close
Date,,,,
2023-01-02,12.08611,1.75146,3.34982,428.95
2023-01-03,12.20866,1.7661,3.31456,434.18
2023-01-04,12.38337,1.79255,3.27019,440.19
2023-01-05,12.38649,1.78952,3.27405,439.33
2023-01-06,12.5375,1.81211,3.24213,444.42

### Lasketaan Index_Log_Return Index_Price_Close avulla

In [3]:
df_index['Index_Log_Return'] = np.log(df_index['Price Close'] / df_index['Price Close'].shift(1))

In [4]:
df_index

.STOXX,Calculated PE Ratio,Calculated Price to Book,Calculated Index Dividend Yield,Price Close,Index_Log_Return
Date,,,,,
2023-01-02,12.08611,1.75146,3.34982,428.95,<NA>
2023-01-03,12.20866,1.7661,3.31456,434.18,0.012119
2023-01-04,12.38337,1.79255,3.27019,440.19,0.013747
2023-01-05,12.38649,1.78952,3.27405,439.33,-0.001956
2023-01-06,12.5375,1.81211,3.24213,444.42,0.011519
...,...,...,...,...,...
2026-02-27,18.53801,0.0001,2.87968,633.85,0.001058
2026-03-02,18.2394,<NA>,2.9297,623.36,-0.016688
2026-03-03,17.66224,2.24125,3.02473,604.44,-0.030822
2026-03-04,17.89812,2.27157,2.99208,612.71,0.013589
2026-03-05,17.65632,2.24212,3.03489,604.83,-0.012944

In [5]:
df_index.isna().sum()

.STOXX
Calculated PE Ratio                10
Calculated Price to Book           11
Calculated Index Dividend Yield     8
Price Close                        15
Index_Log_Return                   25
dtype: int64

## Tallenetaan .csv muodossa

In [6]:
df_index.to_csv('df_index.csv', index=True)

In [7]:
# chunk = 50

universe = [".STOXX"]

fields = [
    "TR.Index_PE_RTRS.date",
    "TR.Index_PRICE_TO_BOOK_RTRS",
    "TR.Index_DIV_YLD_RTRS",
    "TR.PriceClose"
]

# Manuaalisesti 

results = []

# for i in range(0, len(universe), chunk):
#     chunk_universe = universe[i:i + chunk]
#     df_index = rd.get_history(
#         universe=chunk_universe,
#         fields=fields,
#         start="2023-01-01",
#         end="2026-03-05",
#         interval="1D"  
#     )
#     results.append(df_index)
#     time.sleep(1)  # Odota hetki ennen seuraavaa pyyntöä


params = {
    "SDate": "2025-01-01",
    "EDate": "2026-03-05",
    "Frq": "D",
    "Curn": "EUR"
}

df_index = rd.get_data(
    universe=universe,
    fields=fields,
    parameters=params
)

df_index.head()

,Instrument,Date,Calculated Price to Book,Calculated Index Dividend Yield,Price Close
0,.STOXX,2025-01-01,1.94941,3.37061,507.62
1,.STOXX,2025-01-02,1.95835,3.34947,510.67
2,.STOXX,2025-01-03,1.94419,3.37115,508.19
3,.STOXX,2025-01-06,1.96695,3.33564,513.02
4,.STOXX,2025-01-07,1.97139,3.32465,514.67

In [8]:
df_index.isna().sum()

Instrument                         0
Date                               0
Calculated Price to Book           1
Calculated Index Dividend Yield    0
Price Close                        0
dtype: int64

In [9]:
df_index.to_csv('df_index2.csv', index=True)

In [10]:
df_index.head()

,Instrument,Date,Calculated Price to Book,Calculated Index Dividend Yield,Price Close
0,.STOXX,2025-01-01,1.94941,3.37061,507.62
1,.STOXX,2025-01-02,1.95835,3.34947,510.67
2,.STOXX,2025-01-03,1.94419,3.37115,508.19
3,.STOXX,2025-01-06,1.96695,3.33564,513.02
4,.STOXX,2025-01-07,1.97139,3.32465,514.67